version: '2'
services:
 marcel-php:
   container_name: marcel-php
   build: ./docker/php/
   expose:
     - 9000
   volumes_from:
     - marcel-data
 marcel-nginx:
   container_name: marcel-nginx
   build: ./docker/nginx/
   ports:
     - 80:80
     - 443:443
   volumes_from:
     - marcel-data
   depends_on:
     - marcel-php
     - marcel-database
 marcel-data:
   container_name: marcel-data
   image: busybox
   volumes:
     - .:/development
   command: /bin/true
 marcel-development:
   build: ./docker/development
   image: marcel-development
   volumes_from:
     - marcel-data
   command: /bin/true
 marcel-database:
   container_name: marcel-database
   environment:
     MYSQL_DATABASE: pattasoebroto
     MYSQL_PASSWORD: development_password
     MYSQL_ROOT_PASSWORD: development
     MYSQL_USER: development_user
   image: mysql:5.7
   ports:
    - 3306:3306
